version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'asmit99/tweety'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    platform: linux/arm64
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tweety'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./.db:/var/lib/mysql
